// common
const LOGIN = "LOGIN" as never;
const HOME = "HOME" as never;

// transport
const TRANSPORT_STACK = "TRANSPORT_STACK" as never;
const TRANSPORT_DEFAULT = "TRANSPORT_DEFAULT" as never;
const TRANSPORT_DISPLAY = "TRANSPORT_DISPLAY" as never;
const BIRTHDAY_SCREEN = "BIRTHDAY_SCREEN" as never;
const CALENDAR_SCREEN = "CALENDAR_SCREEN" as never;
const CARTOMANCY_SCREEN = "CARTOMANCY_SCREEN" as never;

export {
  LOGIN,
  HOME,
  TRANSPORT_STACK,
  TRANSPORT_DEFAULT,
  TRANSPORT_DISPLAY,
  BIRTHDAY_SCREEN,
  CALENDAR_SCREEN,
  CARTOMANCY_SCREEN
}